### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fatifan** [nxvvvv/warp-plus#12]
Error when connecting server...

**Comment by djmjd** [comment]
same issue here

**Comment by nxvvvv** [comment]
Fixed it with the latest [update](https://github.com/nxvvvv/warp-plus/commit/d3e5aab3a06882a269e751e58a8a7071f9477f19) :)

Just click run again and it will run: 
![image](https://github.com/nxvvvv/warp-plus/assets/34748927/e166ec91-0f3c-44d0-8f06-ef42d71da7e2)

**Comment by Fatifan** [comment]
![Screenshot_20240109-051500_Chrome](https://github.com/nxvvvv/warp-plus/assets/125193909/9d2f1e7c-768a-4e24-93fe-1e2aac384eca)

**Comment by nxvvvv** [comment]
![Screenshot 2024-01-09 123644](https://github.com/nxvvvv/warp-plus/assets/34748927/901a32ed-794f-41e2-ad82-b82d14517347)

**Comment by nxvvvv** [comment]
You used the ID right, as said in the readme, if you use key or anything else instead of ID, it will show this error. 

>Open the app and just connect to 1.1.1.1 (by clicking the button in the middle) if you haven't done it yet.
Now click the sandwich button on the right top of the screen.
Then click Advanced.
Now click Diagnostics and long press the ID under "CLIENT CONFIGURATION" and copy it.
Now run the program and paste the ID when asked.
Enjoy the free WARP+ GBs!!

**Comment by Fatifan** [comment]
Thanks
